### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'start'

### ISSUE THREAD

**Issue by matheusclmb** [XanOpiat/Python-CSGO-Cheat#107]
Doesn't know if it's up to date, but whenever i try to run on IDE or terminal i get the following error:

`Traceback (most recent call last):
  File "C:\Users\persa\Desktop\Python-CSGO-Cheat-main\ProjectX_V2.py", line 8, in <module>
    from Classes.PlayerVars import *
  File "C:\Users\persa\Desktop\Python-CSGO-Cheat-main\Classes\PlayerVars.py", line 1, in <module>
    from Utils.Offsets import *
  File "C:\Users\persa\Desktop\Python-CSGO-Cheat-main\Utils\Offsets.py", line 87, in <module>
    dwViewMatrix = get_sig(pm1, "client.dll", bytes(PatternDict["dwViewMatrix"], encoding="raw_unicode_escape"), 176, 3)
  File "C:\Users\persa\Desktop\Python-CSGO-Cheat-main\Utils\Offsets.py", line 48, in get_sig
    match = re.search(pattern, bytes).start()
AttributeError: 'NoneType' object has no attribute 'start'`

Any help?

**Comment by XanOpiat** [comment]
dwViewMatrix sometimes has problems.
restarting pc and game should fix it
