### ISSUE TITLE
some weird error please check 

### ISSUE THREAD

**Issue by kevinN756** [XanOpiat/Python-CSGO-Cheat#115]
Traceback (most recent call last):
  File "C:\Users\Ali\Downloads\Python-CSGO-Cheat-main\Python-CSGO-Cheat-main\ProjectX_V2.py", line 8, in <module>
    from Classes.PlayerVars import *
  File "C:\Users\Ali\Downloads\Python-CSGO-Cheat-main\Python-CSGO-Cheat-main\Classes\PlayerVars.py", line 1, in <module>
    from Utils.Offsets import *
  File "C:\Users\Ali\Downloads\Python-CSGO-Cheat-main\Python-CSGO-Cheat-main\Utils\Offsets.py", line 75, in <module>
    dwLocalPlayer = get_sig(pm1, "client.dll", bytes(PatternDict["dwLocalPlayer"], encoding="raw_unicode_escape"), 4, 3)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ali\Downloads\Python-CSGO-Cheat-main\Python-CSGO-Cheat-main\Utils\Offsets.py", line 47, in get_sig
    bytes = pm.read_bytes(module.lpBaseOfDll, module.SizeOfImage)
                          ^^^^^^^^^^^^^^^^^^
                          
                          
                          after i ran it with faceit, it started giving this error, and couldnt work anymore inside csgo, i deleted file, downloaded again, nothing is working, please help

**Comment by XanOpiat** [comment]
Obviously you cant run the cheat with faceit but it should still be working finde with vac.

**Comment by XanOpiat** [comment]
@kevinN756 maybe you could provide the full error message?

**Comment by marian-dev0** [comment]
I uploaded the updated version here:
[https://github.com/marian-dev0/CSGO-Mod-Menu](https://github.com/marian-dev0/CSGO-Mod-Menu)..
