### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by GeoPvN** [XanOpiat/Python-CSGO-Cheat#47]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\pymem\__init__.py", line 959, in write_float
    pymem.memory.write_float(self.process_handle, address, value)
  File "C:\Program Files\Python39\lib\site-packages\pymem\memory.py", line 826, in write_float
    res = write_bytes(handle, address, value, length)
  File "C:\Program Files\Python39\lib\site-packages\pymem\memory.py", line 588, in write_bytes
    raise pymem.exception.WinAPIError(error_code)
pymem.exception.WinAPIError: Windows api error, error_code: 998

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Admin\Desktop\Python\ProjectX.py", line 566, in main
    pm.write_float( glow_manager + entity_glow * 0x38 + 0x4, float( r ) )  # R
  File "C:\Program Files\Python39\lib\site-packages\pymem\__init__.py", line 961, in write_float
    raise pymem.exception.MemoryWriteError(address, value, e.error_code)
pymem.exception.MemoryWriteError: Could not write memory at: 284, length: 0.0 - GetLastError: 998

**Comment by XanOpiat** [comment]
Updated offsets, should be working again
