### ISSUE TITLE
pymem.exception.CouldNotOpenProcess

### ISSUE THREAD

**Issue by cookie0X** [XanOpiat/Python-CSGO-Cheat#58]
so my problem is that the cheat worked but now it just tell´s me :

Traceback (most recent call last):
  File "C:\Users\juerg\OneDrive\Desktop\cs_hax\chinaversion.py", line 65, in <module>
    pm = pymem.Pymem("csgo.exe")
  File "E:\python\lib\site-packages\pymem\__init__.py", line 44, in __init__
    self.open_process_from_name(process_name)
  File "E:\python\lib\site-packages\pymem\__init__.py", line 204, in open_process_from_name
    self.open_process_from_id(self.process_id)
  File "E:\python\lib\site-packages\pymem\__init__.py", line 226, in open_process_from_id
    raise pymem.exception.CouldNotOpenProcess(self.process_id)
pymem.exception.CouldNotOpenProcess: Could not open process: 15836

pls help is there a fix =?

**Comment by XanOpiat** [comment]
ok, for me everything is still working, there are some things you can try tho.
1. Run your cmd as administrator
2. Dont use the chinaversion.py file. it doesnt have automated offsets, because of the chinese firewall
3. Make sure csgo is open i guess
