### ISSUE TITLE
Could not open process:4336

### ISSUE THREAD

**Issue by AlexSh29** [XanOpiat/Python-CSGO-Cheat#79]
C:\Users\Alex She\Desktop> python OldCheatVersion.py
foqnmwordqowjm333q3q3q3q5q4q3
85
Traceback (most recent call last):
  File "OldCheatVersion.py", line 721, in <module>
    ui = Ui_MainWindow()
  File "OldCheatVersion.py", line 170, in __init__
    self.pm = pymem.Pymem( "csgo.exe" )
  File "F:\PythonNew\lib\site-packages\pymem\__init__.py", line 44, in __init__
    self.open_process_from_name(process_name)
  File "F:\PythonNew\lib\site-packages\pymem\__init__.py", line 204, in open_process_from_name
    self.open_process_from_id(self.process_id)
  File "F:\PythonNew\lib\site-packages\pymem\__init__.py", line 226, in open_process_from_id
    raise pymem.exception.CouldNotOpenProcess(self.process_id)
pymem.exception.CouldNotOpenProcess: Could not open process: 4336

**Comment by XanOpiat** [comment]
is csgo open?

**Comment by XanOpiat** [comment]
and are you running as admin?
