### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ElOxo** [XanOpiat/Python-CSGO-Cheat#86]
Traceback (most recent call last):
  File "ProjectX_V2.py", line 3, in <module>
    from Utils.Bhop import *
  File "C:\Users\***\Downloads\Python-CSGO-Cheat-main\Python-CSGO-Cheat-main\Utils\Bhop.py", line 1, in <module>    
    from Utils.Offsets import *
  File "C:\Users\***\Downloads\Python-CSGO-Cheat-main\Python-CSGO-Cheat-main\Utils\Offsets.py", line 65, in <module>
    dwLocalPlayer = get_sig( pm1, "client.dll",
  File "C:\Users\***\Downloads\Python-CSGO-Cheat-main\Python-CSGO-Cheat-main\Utils\Offsets.py", line 40, in get_sig 
    match = re.search( pattern, bytes ).start()
AttributeError: 'NoneType' object has no attribute 'start'

**Comment by XanOpiat** [comment]
restart your game

**Comment by ElOxo** [comment]
jo hatte das nicht probiert :D 

Als bald guten Rutsch ins neue Jahr ;)

**Comment by XanOpiat** [comment]
Dir auch :)
