### ISSUE TITLE
Trotz mehrmaligem Neustart von CS erhalte ich den NoneType error

### ISSUE THREAD

**Issue by ElOxo** [XanOpiat/Python-CSGO-Cheat#92]
Traceback (most recent call last):
  File "ProjectX_V2.py", line 3, in <module>
    from Utils.Bhop import *
  File "D:\Sonstiges\CS-GO\new Cheat\Python-CSGO-Cheat\Utils\Bhop.py", line 1, in <module>
    from Utils.Offsets import *
  File "D:\Sonstiges\CS-GO\new Cheat\Python-CSGO-Cheat\Utils\Offsets.py", line 69, in <module>
    dwEntityList = get_sig( pm1, "client.dll",bytes(PatternDict["dwEntityList"], encoding="raw_unicode_escape"), 0, 1 )
  File "D:\Sonstiges\CS-GO\new Cheat\Python-CSGO-Cheat\Utils\Offsets.py", line 41, in get_sig
    match = re.search( pattern, bytes ).start()
AttributeError: 'NoneType' object has no attribute 'start'

**Comment by XanOpiat** [comment]
Sehr wierder error in letzter zeit mit dem dwEntityList Offset, pattern auf hazedumper ist nich aktuell/korrekt, da ich selbst nicht weiß wie man das fixen kann, habe ich in der neuesten Version vom cheat das offset einfach gehardcoded

**Comment by XanOpiat** [comment]
das lass ich solange so bis ich herausgefunden habe warum der import fehlschlägt
